### ISSUE TITLE
No trade execution due to failed market order [unsupported filling mode] in MT5 Strategy Tester

### ISSUE THREAD

**Issue by 1GitHub77** [Bongo-Seakhoa/mql5_ea#1]
Hi everyone,

your project seems very interesting.
I only have problems to backtest it, I know you did not mentioned it, for Strategy Tester of Metatrader 5.
Will the backtest work in MT5 Strategy Tester?

I tested it on ICTrading Broker on XAUUSD Symbol (15Min TF) , 
but I get an error for every market order "[Unsupported filling mode]" see screenshot below.

I tried to add the filling mode on the source code section on populatoin of trade request:
request.type_filling = ORDER_FILLING_IOC;

But this does not work - same error here.

Any ideas to fix that issue?

Thanks in advance

![mt5_error_testEA](https://github.com/user-attachments/assets/4d74907b-b960-4721-a3c2-da49df3f8a8c)

**Comment by Bongo-Seakhoa** [comment]
Yes please use Metatrader's strategy tester and if you can please validate that the method is following the latest documentation. I haven't updated it in a while and I see that the filing method may be outdated from when I uploaded the code.
